name: build-apk
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK packages
        run: sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # Pastikan AndroidX aktif (dibuatkan jika belum ke-commit)
      - name: Ensure root gradle.properties
        run: |
          printf "org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8\nandroid.useAndroidX=true\nandroid.enableJetifier=true\n" > gradle.properties
          echo "---- gradle.properties (root) ----"
          cat gradle.properties

      - name: Ensure user gradle.properties
        run: |
          mkdir -p ~/.gradle
          printf "org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8\nandroid.useAndroidX=true\nandroid.enableJetifier=true\n" > ~/.gradle/gradle.properties
          echo "---- ~/.gradle/gradle.properties ----"
          cat ~/.gradle/gradle.properties

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.7

      - name: Build debug APK
        run: gradle :app:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
